---
title: "DSlecture15_plotly example"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Example of plotly
Nyc airbnb data
```{r, message = FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```


```{r}
data("nyc_airbnb")
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location/2) %>% 
  select(neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>% 
  filter(
    neighbourhood_group == "Manhattan",
    price %in% 100:500,
    room_type == "Entire home/apt"
  ) %>% 
  drop_na(rating)
```

# plotly plots

## scatter plots

```{r}
nyc_airbnb %>% 
  mutate(text_label = str_c("Price : $", price, "\nRating:", rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~ text_label, 
    alpha = 0.5, type = "scatter", mode = "markers")
```

## boxplot

```{r}
nyc_airbnb %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(
    y = ~ price,
    x = ~ neighbourhood,
    type = "box",
    color = ~neighbourhood,
    colors = "viridis"
  )
```

```{r}
nyc_airbnb %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(
    y = ~ price,
    x = ~ neighbourhood,
    type = "violin",
    color = ~neighbourhood,
    colors = "viridis"
  )
```

## bar plot

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(
    x= ~ neighbourhood,
    y= ~ n,
    type = "bar",
    color = ~ neighbourhood,
    colors = "viridis"
  )
```




